### ISSUE TITLE
not thread/fork safe?

### ISSUE THREAD

**Issue by garu** [PerlDancer/Dancer-Session-Cookie#3]
Hello!

I ran into a pretty serious issue where different, concurring users where sometimes getting another user's session data. I could only see it in production, where Dancer 1 was running via:

```
 start_server [some_options] -- starman -E production --preload_app --workers 10
```

@xsawyerx helped me debug and, as it turns out, he may have found that Dancer-Session-Cookie doesn't play it safe in a threaded/forked environment.

I'm going to leave the details to @xsawyerx himself, but since there was no mention on the pod about this, I'm assuming it's a bug. And if this is the case, other people might have being dealing with the issue in production, which could pose as a security issue too.

Thanks!

**Comment by yanick** [comment]
Activity on this ticket seems to be pretty dead, and we have no example to work on. Until something else resurface, I'll be harsh and close the ticket.
