### ISSUE TITLE
name section is missing from README.pod

### ISSUE THREAD

**Issue by mestia** [PerlDancer/Dancer-Session-Cookie#6]
Hello,
as the README.pod is used to generate the Dancer::Session::README man page, it should also have a "NAME" section, which is parsed by lexgrog and used to generate a database that's queried by commands like apropos and whatis. 

thank you.

**Comment by yanick** [comment]
Actually, getting the information from lib/Dancer/Session/Cookie.pm is even better. Removed the duplicate 'README' from the root directory.
